# Generated by Django 2.2.16 on 2022-06-09 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220609_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 9, 16, 40, 45, 404445, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
